//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Cadastro_de_motorista
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newmotorista
    {
        public int Motid { get; set; }
        public string Motnome { get; set; }
        public string Motsobrenome { get; set; }
        public string Motcaminhao { get; set; }
        public string Motendereco { get; set; }
        public string Motmarca { get; set; }
        public string Motmodelo { get; set; }
        public string Motnumcaminhao { get; set; }
        public string Moteixos { get; set; }
    }
}
